export interface IEndorsementDTO {
    createdAt: string,
    number: string,
    registrationNumber: string,
    insured: boolean,
    type: string,
    authorizer: string,
    creator: string,
}

export const endorsementList: IEndorsementDTO[] = [
    {
        createdAt: '9/8/2023',
        number: '758',
        registrationNumber: 'WBAVM5C53EV908111',
        insured: true,
        type: 'UMPQ',
        authorizer: 'Robby Cush',
        creator: 'Amara Jahnig',
    },
    {
        createdAt: '7/23/2023',
        number: '06',
        registrationNumber: 'JTDKN3DU5B0042496',
        insured: true,
        type: 'HCI',
        authorizer: 'Rachael Burleton',
        creator: 'Elsy Upton',
    },
    {
        createdAt: '9/28/2023',
        number: '461',
        registrationNumber: '1GYS3GEF7BR188045',
        insured: false,
        type: 'SBRAP',
        authorizer: 'Mariam Nisbith',
        creator: 'Porty Oganesian',
    },
    {
        createdAt: '10/13/2023',
        number: '66046',
        registrationNumber: '2C3CCAJT4CH383075',
        insured: true,
        type: 'FIVN',
        authorizer: 'Val Croley',
        creator: 'Cate Blaxeland',
    },
    {
        createdAt: '4/19/2023',
        number: '3871',
        registrationNumber: 'WP1AE2A23CL483161',
        insured: true,
        type: 'WTTR',
        authorizer: 'Mathian Harbinson',
        creator: 'Reta Westnedge',
    },
    {
        createdAt: '10/13/2023',
        number: '10241',
        registrationNumber: 'KNAFT4A26C5905842',
        insured: true,
        type: 'TMK^B',
        authorizer: 'Mathian Lemme',
        creator: 'Jaimie Dulieu',
    },
    {
        createdAt: '6/26/2023',
        number: '33820',
        registrationNumber: 'TRUWC28N121272878',
        insured: false,
        type: 'LMRKO',
        authorizer: 'Fulton Clinkard',
        creator: 'Charmian Meadley',
    },
    {
        createdAt: '4/9/2023',
        number: '29',
        registrationNumber: '2C3CA6CT6AH729902',
        insured: true,
        type: 'SCZ',
        authorizer: 'Jobi Goathrop',
        creator: 'Dion Leborgne',
    },
    {
        createdAt: '3/26/2023',
        number: '834',
        registrationNumber: '5TFBY5F19CX254879',
        insured: false,
        type: 'CTBI',
        authorizer: 'Bette-ann Gawler',
        creator: 'Beaufort Mirralls',
    },
    {
        createdAt: '1/16/2023',
        number: '240',
        registrationNumber: '1G6DX67D760947332',
        insured: true,
        type: 'VST',
        authorizer: 'Lars Filkov',
        creator: 'Pasquale Duffrie',
    },
    {
        createdAt: '9/29/2023',
        number: '57727',
        registrationNumber: '19UUA8F76CA325771',
        insured: true,
        type: 'AMOV',
        authorizer: 'Demetra Naish',
        creator: 'Elizabet Gammett',
    },
    {
        createdAt: '10/1/2023',
        number: '27598',
        registrationNumber: '3C6JD7DP5CG866745',
        insured: true,
        type: 'NBR',
        authorizer: 'Salim Avrasin',
        creator: 'Kathryn Leile',
    },
    {
        createdAt: '6/5/2023',
        number: '25',
        registrationNumber: 'WBADS33403G401200',
        insured: true,
        type: 'XCO',
        authorizer: 'Terence Kondrat',
        creator: 'Yehudi Olivier',
    },
    {
        createdAt: '6/17/2023',
        number: '87645',
        registrationNumber: 'WBACK73481L128675',
        insured: false,
        type: 'KEQU',
        authorizer: 'Will Koenen',
        creator: 'Roth Loffill',
    },
    {
        createdAt: '5/8/2023',
        number: '3',
        registrationNumber: '3C4PDCEG3ET148504',
        insured: false,
        type: 'ARGS',
        authorizer: 'Athene Mitchiner',
        creator: 'Rockwell Lindenberg',
    },
    {
        createdAt: '11/2/2023',
        number: '81',
        registrationNumber: 'WBAFV3C59ED119117',
        insured: true,
        type: 'BSX',
        authorizer: 'Marius Chadbourne',
        creator: 'Gerry Stuchburie',
    },
    {
        createdAt: '12/14/2022',
        number: '706',
        registrationNumber: '1GYUKJEF4AR761670',
        insured: true,
        type: 'THO',
        authorizer: 'Adrea Badrick',
        creator: 'Norry Rowes',
    },
    {
        createdAt: '9/18/2023',
        number: '59',
        registrationNumber: '1FTSX2A5XAE320745',
        insured: true,
        type: 'URRE',
        authorizer: 'Stacia Quiney',
        creator: 'Cordi Thurlow',
    },
    {
        createdAt: '6/6/2023',
        number: '49',
        registrationNumber: 'TRUDD38J781498519',
        insured: true,
        type: 'AVP',
        authorizer: 'Jacky Suche',
        creator: 'Petronella Duckhouse',
    },
    {
        createdAt: '5/11/2023',
        number: '8',
        registrationNumber: 'WAUFMBFC3EN103514',
        insured: true,
        type: 'LEN.B',
        authorizer: 'Dody Bohlens',
        creator: 'Alric Wharram',
    },
];